// <auto-generated />
namespace Ivo.OefenfirmaCMS.lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wijzigprijsprod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wijzigprijsprod));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071058493_wijzigprijsprod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
