// <auto-generated />
namespace Ivo.OefenfirmaCMS.lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbrole));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120917080_dbrole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
